# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlore < Formula
  desc "Accumulated knowledge for AI-assisted codebases"
  homepage "https://github.com/EduardMaghakyan/gitlore"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EduardMaghakyan/gitlore/releases/download/v0.1.0/gitlore_0.1.0_darwin_amd64.tar.gz"
      sha256 "370bbdd2e0155d812eca16388a47e2ea96ce3d59585d7c31a8c2c0aebd447dff"

      define_method(:install) do
        bin.install "gitlore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EduardMaghakyan/gitlore/releases/download/v0.1.0/gitlore_0.1.0_darwin_arm64.tar.gz"
      sha256 "9526179861a62399e0d82d20f2ff118f64158a1a26c67b29c4ec27ce82234367"

      define_method(:install) do
        bin.install "gitlore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardMaghakyan/gitlore/releases/download/v0.1.0/gitlore_0.1.0_linux_amd64.tar.gz"
      sha256 "d325522b5e603d9004c5d16039fc12a13e609c8e44ec4ad8fc3fb947a4676f2f"
      define_method(:install) do
        bin.install "gitlore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EduardMaghakyan/gitlore/releases/download/v0.1.0/gitlore_0.1.0_linux_arm64.tar.gz"
      sha256 "57d494769f311556361540c1d3ae203bc1b8a6db764079043fde6fca3a8dca6d"
      define_method(:install) do
        bin.install "gitlore"
      end
    end
  end

  test do
    system "#{bin}/gitlore", "version"
  end
end
